# Generated by Django 5.2.4 on 2025-07-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('razao_social', models.CharField(blank=True, max_length=150)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_contrato', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('qtd_funcionarios', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
