# Generated by Django 5.2.4 on 2025-07-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_evolution_instance_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='evolution_instance_name',
            new_name='evolution_instance_id',
        ),
    ]
